config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "messages#index"
  resources :posts, only: [:index, :new, :create]
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  validates :country, presence: true
  belongs_to :region
  has_many :post
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  validates :total_rate, presence: true
  belongs_to :user
  belongs_to :country
end

app/models/region.rb
class Region < ApplicationRecord
  validates :region, presence: true
  has_many :country
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
    @user = current_user
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
  end

  private
  def post_params
    params.require(:post).permit( :detailed_place, :visit_date, :visit_cost, :visit_length, 
                                  :total_rate, :food_rate, :hotel_rate, :entertainment_rate, 
                                  :sightseeing_rate, :language, :content, :climate)
                                  .merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @name = current_user.name
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JapaSty</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JapaSty</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class=body>

  <div class="fixed-header">
    <div class="site-title">
      <h1>JapaSty</h1>
    </div>
  </div>

  <div class="sidebar">

  </div>

  <div class="main">

    <footer>
      <div class="main-menu">
        
        <ul class="main-menu__list">
          <li class="main-menu__list-item">
            <div class="main-menu__list-item__content">
              <h1 class="logo"><a href="/">Travelungo</a></h1>
            </div>
          </li>
          <li class="main-menu__list-item">
            <div class="main-menu__list-item__content">
              <%= link_to "投稿一覧", posts_path, class: 'post' %>
            </div>
          </li>

        <% if user_signed_in? %>

          <li class="main-menu__list-item">
            <div class="main-menu__list-item__content">
            <span>
              <%= link_to "マイページ", "/users/#{current_user.id}" %>
            </span>
            </div>
          </li>
          <li class="main-menu__list-item">
            <div class="main-menu__list-item__content">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </div>
          </li>
          <li class="main-menu__list-item">
            <div class="main-menu__list-item__content">
              <%= link_to "新規投稿", new_post_path, class: "post" %>
            </div>
          </li>

        <% else %>
          
          <li class="main-menu__list-item">
            <div class="main-menu__list-item__content">
              <%= link_to "ログイン", new_user_session_path, class: 'post' %>
            </div>
          </li>
          <li class="main-menu__list-item">
            <div class="main-menu__list-item__content">
              <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
            </div>
          </li>
                  
        <% end %>
            
        </ul>
      </div>

    </footer>
  </div>

</body>
</html>

app/views/posts/_post.html.erb
<div class="main__contents-posts__post">
    <div class="main__contents-posts__post-rate">
    <a href="/users/<%= @post.user.id %>">
        <span><%= @post.user.name %></span>
      <h1><%= post.detailed_place %></h1><br>
      <%= post.total_rate.to_s %>
    </div>
    <div class="main__contents-posts__post-date">
      <%= post.visit_date %>
    </div>
    <div class="main__contents-posts__post-length">
      <%= post.visit_length %>
    </div>
    <div class="main__contents-posts__post-cost">
      <%= post.visit_cost %>
    </div>
    <div class="main__contents-posts__post-maintext">
      <%= post.content %>
    </div>
    <div class="main__contents-posts__post-created_at">
      <%= post.created_at %>
    </div>
</div>

app/views/posts/create.html.erb
<html>
<body>
  <div class="main__contents">
    <h1>投稿が完了しました</h1>
  </div>

  <%= render partial: "shared/footer_menu" %>
</div>
<%= render partial: "shared/side_bar" %>
</body>
</html>

app/views/posts/index.html.erb
<html>
<body>
  <div class="main__contents">
    <div class="main__contents-posts">
      <% @posts.each do |post| %>
        <%= render partial: "post", collection: @posts %>
      <% end%>
          <div class="content__right">
            <%# <%= post.total_rate.to_s %>
          </div>
          <div class="content__right">
            <%# <%= post.content %>
          </div>
          <div class="content__right">
            <%# <%= post.created_at %>
          </div>
    </div>
  </div>

  <%= render partial: "shared/footer_menu" %>
</div>
<%= render partial: "shared/side_bar" %>
</body>
</html>

app/views/posts/new.html.erb
<%= render partial: "shared/side_bar" %>
<%= render partial: "shared/footer_menu" %>

<div class="main">
  <div class="main-content">
    
    <div class="container">
    <%= form_for @post do |form| %>
      <h1>新規投稿</h1>
      <p>
      <select name="example">
      <option value="選択肢1">アジア</option>
      <option value="選択肢2">オセアニア</option>
      <option value="選択肢3">ハワイ・太平洋諸島</option>
      <option value="選択肢4">北米</option>
      <option value="選択肢5">中南米</option>
      <option value="選択肢6">ヨーロッパ</option>
      <option value="選択肢7">中東</option>
      <option value="選択肢8">アフリカ</option>
      </select>
      </p>
      <%= form.text_field :country, placeholder: "詳細な場所" %><br>
      <%= form.select :visit_date, ['2010'], prompt: '' %><br>
      <%= form.select :visit_cost, ['3万円未満', '3~5万円', '5~7万円', '7~10万円', '10~15万円', '15~20万円', '20~25万円', '25~30万円', '30~40万円', '40~50万円', '50万円以上'], prompt: '選択してください' %><br>
      <%= form.select :visit_length, ['1日未満', '1~3日', '3~5日', '5日~7日', '7~10日', '10~15日', '15~20日', '20日以上'], prompt: '選択してください' %><br>
      <%= form.text_field :language, placeholder: "言葉について" %><br>
      <div class="images">
      <label class="image-area" for="post_image">
        <%= fa_icon("image 4x") %>
        <input class="hidden" type="file" name="message[image]" id="post_image">
      </label>
      </div>
      
      <div class="total_rate">
        <div class="field_title">
          <p>総合点</p>
        </div>
        <div class="field" id="star1">
         <%= form.hidden_field :total_rate, class: "form-control"  %><br>
        </div>
        <script>
        $('#star1').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'post[total_rate]',
          half: true,
        });
        </script>
      </div>
        
      <div class="food_rate">
        <div class="field_title">
          <p>食事の良さ</p>
        </div>
        <div class="field" id="star2">
        <%= form.hidden_field :food_rate, class: "form-control"  %><br>
        </div>
        <script>
        $('#star2').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'post[food_rate]',
          half: true,
        });
        </script>
      </div>

        <div class="hotel_rate">
          <div class="field_title">
            <p>宿泊の良さ</p>
          </div>
          <div class="field" id="star3">
          <%= form.hidden_field :hotel_rate, class: "form-control"  %><br>
          </div>
          <script>
          $('#star3').raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'post[hotel_rate]',
            half: true,
          });
          </script>
        </div>

        <div class="entertainment_rate">
        <div class="field_title">
          <p>エンターテインメント</p>
        </div>
        <div class="field" id="star4">
         <%= form.hidden_field :entertainment_rate, class: "form-control"  %><br>
        </div>
        <script>
        $('#star4').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'post[entertainment_rate]',
          half: true,
        });
        </script>

        <div class="sightseeing_rate">
        <div class="field_title">
          <p>観光の良さ</p>
        </div>
        <div class="field" id="star5">
         <%= form.hidden_field :sightseeing_rate, class: "form-control"  %><br>
        </div>
        <script>
        $('#star5').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'post[sightseeing_rate]',
          half: true,
        });
        </script>

        <script src="/js/jquery.min.js"></script>
        <script src="/js/jquery.raty.js"></script>
        
        
 
      </div>
      
      <%= form.text_area :content, placeholder: "text", size: "60x5" %><br>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
      </div>
    </div>
  </div>
</div>



<%#= form.label :star %>
            <%#= form.hidden_field :star, id: :review_star %>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer_menu.html.erb
<footer>
  <div class="main-menu">
    
    <ul class="main-menu__list">
      <li class="main-menu__list-item">
        <div class="main-menu__list-item__content">
          <h1 class="logo"><a href="/">Travelungo</a></h1>
        </div>
      </li>
      <li class="main-menu__list-item">
        <div class="main-menu__list-item__content">
          <%= link_to "投稿一覧", posts_path, class: 'post' %>
        </div>
      </li>

    <% if user_signed_in? %>

      <li class="main-menu__list-item">
        <div class="main-menu__list-item__content">
        <span>
          <%#= link_to "マイページ", "/users/#{current_user.id}" %>
          <%#= link_to "マイページ", current_user.name, user_path(current_user) %>
          <%= link_to "マイページ", user_path(current_user) %>
        </span>
        </div>
      </li>
      <li class="main-menu__list-item">
        <div class="main-menu__list-item__content">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </div>
      </li>
      <li class="main-menu__list-item">
        <div class="main-menu__list-item__content">
          <%= link_to "新規投稿", new_post_path, class: "post" %>
        </div>
      </li>

    <% else %>
      
      <li class="main-menu__list-item">
        <div class="main-menu__list-item__content">
          <%= link_to "ログイン", new_user_session_path, class: 'post' %>
        </div>
      </li>
      <li class="main-menu__list-item">
        <div class="main-menu__list-item__content">
          <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
        </div>
      </li>
              
    <% end %>
        
    </ul>
  </div>

</footer>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/shared/_side_bar.html.erb
<div class="sidebar">
<% %>
  <div class="sidebar-main">
    <div class="page-wrapper chiller-theme toggled">
  <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
    <i class="fas fa-bars"></i>
  </a>
  <nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">
      <div class="sidebar-brand">
        <%= link_to "traveller menu", root_path %>
        <div id="close-sidebar">
        </div>
      </div>
      <div class="sidebar-header">
        <div class="user-pic">
          <img class="img-responsive img-rounded" src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg" alt="User picture">
        </div>
        <div class="user-info">
          <span class="user-name">
            <strong><%= @user.name %></strong>
          </span>
          
          <span class="user-status">
            <i class="fa fa-circle"></i>
            <span>Login</span>
          </span>

          <span class="user-points">
            <p>旅偏差値 XX</p>
          </span>
        </div>
      </div>
      <!-- sidebar-header  -->
      <div class="sidebar-search">
        <div>
          <div class="input-group">
            <input type="text" class="form-control search-menu" placeholder="Search...">
            <div class="input-group-append">
              <span class="input-group-text">
                <i class="fa fa-search" aria-hidden="true"></i>
              </span>
            </div>
          </div>
        </div>
      </div>
      <!-- sidebar-search  -->
      <div class="sidebar-menu">
        <ul>
          <li class="header-menu">
            <span></span>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-tachometer-alt"></i>
              <span>Dashboard</span>
              <span class="badge badge-pill badge-warning">New</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">Dashboard 1
                    <span class="badge badge-pill badge-success">Pro</span>
                  </a>
                </li>
                <li>
                  <a href="#">Dashboard 2</a>
                </li>
                <li>
                  <a href="#">Dashboard 3</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-shopping-cart"></i>
              <span>E-commerce</span>
              <span class="badge badge-pill badge-danger">3</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">Products

                  </a>
                </li>
                <li>
                  <a href="#">Orders</a>
                </li>
                <li>
                  <a href="#">Credit cart</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="far fa-gem"></i>
              <span>Components</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">General</a>
                </li>
                <li>
                  <a href="#">Panels</a>
                </li>
                <li>
                  <a href="#">Tables</a>
                </li>
                <li>
                  <a href="#">Icons</a>
                </li>
                <li>
                  <a href="#">Forms</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-chart-line"></i>
              <span>Charts</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">Pie chart</a>
                </li>
                <li>
                  <a href="#">Line chart</a>
                </li>
                <li>
                  <a href="#">Bar chart</a>
                </li>
                <li>
                  <a href="#">Histogram</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-globe"></i>
              <span>Maps</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">Google maps</a>
                </li>
                <li>
                  <a href="#">Open street map</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="header-menu">
            <span>新着メッセージ</span>
          </li>
          <li>
            <a href="#">
              <%# <i class="fa fa-book"></i> %>
              <span>ユーザー1</span>
              <span class="badge badge-pill badge-primary"></span>
            </a>
          </li>
          <li>
            <a href="#">
              <%# <i class="fa fa-calendar"></i> %>
              <span>ユーザー2</span>
            </a>
          </li>
          <li>
            <a href="#">
              <%# <i class="fa fa-folder"></i> %>
              <span>ユーザー3</span>
            </a>
          </li>
        </ul>
      </div>
      <!-- sidebar-menu  -->
    </div>
    <!-- sidebar-content  -->
    <div class="sidebar-footer">
      <%# <a href="#">
        <i class="fa fa-bell"></i>
        <span class="badge badge-pill badge-warning notification">3</span>
      </a> %>
      <a href="#">
        <i class="fa fa-envelope"></i>
        <span class="badge badge-pill badge-success notification"></span>
      </a>
      <a href="#">
        <i class="fa fa-cog"></i>
        <%# <span class="badge-sonar"></span> %>
      </a>
      <a href="#">
        <i class="fa fa-star"></i>
      </a>
    </div>
  </nav>
  <!-- sidebar-wrapper  -->
  <%# <main class="page-content">
    <div class="container-fluid">
      <h2>Pro Sidebar</h2>
      <hr>
      <div class="row">
        <div class="form-group col-md-12">
          <p>This is a responsive sidebar template with dropdown menu based on bootstrap 4 framework.</p>
          <p> You can find the complete code on <a href="https://github.com/azouaoui-med/pro-sidebar-template" target="_blank">
              Github</a>, it contains more themes and background image option</p>
        </div>
        <div class="form-group col-md-12">
          <iframe src="https://ghbtns.com/github-btn.html?user=azouaoui-med&repo=pro-sidebar-template&type=star&count=true&size=large" frameborder="0" scrolling="0" width="140px" height="30px"></iframe>
          <iframe src="https://ghbtns.com/github-btn.html?user=azouaoui-med&repo=pro-sidebar-template&type=fork&count=true&size=large" frameborder="0" scrolling="0" width="140px" height="30px"></iframe>
        </div>
      </div>
      <h5>More templates</h5>
      <hr>
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
          <div class="card rounded-0 p-0 shadow-sm">
            <img src="https://user-images.githubusercontent.com/25878302/58369568-a49b2480-7efc-11e9-9ca9-2be44afacda1.png" class="card-img-top rounded-0" alt="Angular pro sidebar">
            <div class="card-body text-center">
              <h6 class="card-title">Angular Pro Sidebar</h6>
              <a href="https://github.com/azouaoui-med/angular-pro-sidebar" target="_blank" class="btn btn-primary btn-sm">Github</a>
              <a href="https://azouaoui-med.github.io/angular-pro-sidebar/demo/" target="_blank" class="btn btn-success btn-sm">Preview</a>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
          <div class="card rounded-0 p-0 shadow-sm">
            <img src="https://user-images.githubusercontent.com/25878302/58369258-33f20900-7ef8-11e9-8ff3-b277cb7ed7b4.PNG" class="card-img-top rounded-0" alt="Angular pro sidebar">
            <div class="card-body text-center">
              <h6 class="card-title">Angular Dashboard</h6>
              <a href="https://github.com/azouaoui-med/lightning-admin-angular" target="_blank" class="btn btn-primary btn-sm">Github</a>
              <a href="https://azouaoui-med.github.io/lightning-admin-angular/demo/" target="_blank" class="btn btn-success btn-sm">Preview</a>
            </div>
          </div>
        </div>
      </div>
    </div>

  </main> %>
  <!-- page-content" -->
</div>
<!-- page-wrapper -->
  </div>
</div>

app/views/shared/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travelungo</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <div class="main">
    <footer>
      <div class="main-menu">
        
        <ul class="main-menu__list">
          <li class="main-menu__list-item">
            <div class="main-menu__list-item__content">
              <h1 class="logo"><a href="/">Travelungo</a></h1>
            </div>
          </li>
          <li class="main-menu__list-item">
            <div class="main-menu__list-item__content">
              <%= link_to "投稿一覧", posts_path, class: 'post' %>
            </div>
          </li>

        <% if user_signed_in? %>

          <li class="main-menu__list-item">
            <div class="main-menu__list-item__content">
            <span>
              <%= link_to "マイページ", "/users/#{current_user.id}" %>
            </span>
            </div>
          </li>
          <li class="main-menu__list-item">
            <div class="main-menu__list-item__content">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </div>
          </li>
          <li class="main-menu__list-item">
            <div class="main-menu__list-item__content">
              <%= link_to "新規投稿", new_post_path, class: "post" %>
            </div>
          </li>

        <% else %>
          
          <li class="main-menu__list-item">
            <div class="main-menu__list-item__content">
              <%= link_to "ログイン", new_user_session_path, class: 'post' %>
            </div>
          </li>
          <li class="main-menu__list-item">
            <div class="main-menu__list-item__content">
              <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
            </div>
          </li>
                  
        <% end %>
            
        </ul>
      </div>

      <div class="main-bottom">
        <p>Copyright 2019.</p>
      </div>
    </footer>
  </div>

</body>
</html>

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", '#', class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/show.html.erb
<%= render partial: "shared/side_bar" %>
<%= render partial: "shared/footer_menu" %>

<div class="main">
  <section class="main-content">

  <div class="main-profile">
    <%= @user.thumbnail_image %>
    <%= @user.name %>
    <%= @user.name %>
    <%= @user.name %>

  <div class="main__user-posts">
    <%= @user.name %>さんの投稿一覧
  </div>
  <% @posts.each do |post| %>
    <div class="main__user-posts__content">
      <div class="content__left">
        <div class="content__left--image"></div>
      </div>
      <div class="content__right">
        <div class="content__right__top">
          <%# <%= link_to post.total_rate, post_path(post.id), class: "content__right__top--title" %> %>
        </div>
        <div class="content__right__bottom">
          <div class="content__right__bottom--userName">
            <%# <%= link_to post.user.name, user_path(post.user), class: "content__right__bottom--userName--btn" %> %>
          </div>
          <div class="content__right__bottom--date">
            <%= post.created_at %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </section>
</div>